services:
  - type: web
    name: rellion-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: MANAGER
        value: "@vehaus"
      - key: PYTHON_VERSION
        value: "3.12.7"

  - type: web
    name: rellion-miniapp
    runtime: static
    rootDir: mini_app
    buildCommand: ""
    staticPublishPath: .
